version: "3"
services:
  opencv_env:
    command: /bin/bash
    build:
      context: ./
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    image: opencv_env:latest